package ch.heigvd.utils.controller;

import ch.heigvd.utils.entity.Membre;
import jakarta.persistence.EntityManager;

public class MembreController {
    static final EntityManager em = AppContextListener.createEntityManager();
    public static void create(Membre membre) {
        // persist the member and get the compteId that will be generated by the database
        em.getTransaction().begin();
        em.persist(membre);
        em.getTransaction().commit();
        em.refresh(membre);
    }
}
