version: '3.8'

networks:
  bdr-net:
    driver: bridge

services:

  # postgresql
  postgresql:
    image: 'bitnami/postgresql:16'
    environment:
      - POSTGRESQL_USERNAME=bdr
      - POSTGRESQL_PASSWORD=bdr
      - POSTGRESQL_DATABASE=bdr
      - POSTGRESQL_POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - bdr-net

  # tomcat
  tomcat:
    image: 'tomcat:10.1.17-jdk17-temurin'
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    volumes:
      - ./target/myamazingfitness.war:/usr/local/tomcat/webapps/myamazingfitness.war
    networks:
      - bdr-net

volumes:
  postgresql_data: