# http://localhost:8080/home

version: '3.8'

networks:
  bdr-net:
    driver: bridge

services:

  postgresql:
    container_name: postgresql
    image: 'bitnami/postgresql:16'
    environment:
      - POSTGRESQL_USERNAME=bdr
      - POSTGRESQL_PASSWORD=bdr
      - POSTGRESQL_DATABASE=bdr
      - POSTGRESQL_POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/tmp/sql
    networks:
      - bdr-net

  myamazingfitness:
    container_name: myamazingfitness
    image: 'ghcr.io/theodrosrun/my-amazing-fitness:latest'
    ports:
      - '8080:8080'
    networks:
      - bdr-net

volumes:
  postgresql_data:
